In [10]:
# Creating Numpy Array using list with array() function
import numpy as np
myarray=np.array([1,2,3,4,5])
print(type(myarray))
print(myarray)
print(myarray.shape)
print(myarray.size)
print(myarray.ndim)
print(myarray.dtype)
sum=0
for i in myarray:
    sum=sum+i
print("Sum:",sum)
print("max:",max(myarray))
print("min:",min(myarray))
n=int(input("Enter element for search"))
if n in myarray:
    print("Found")
else:
    print("not found")


<class 'numpy.ndarray'>
[1 2 3 4 5]
(5,)
5
1
int32
Sum: 15
max: 5
min: 1
Enter element for search4
Found


In [9]:
import numpy as np
myarray=np.array([1,"k",3,4.7,5])
print(type(myarray))
print(myarray)

<class 'numpy.ndarray'>
['1' 'k' '3' '4.7' '5']


In [5]:
# Creating Numpy Array using tuple with array() function
import numpy as np
myarray=np.array((1,2,3,4,5))
print(type(myarray))
print(myarray)
print(myarray.shape)

<class 'numpy.ndarray'>
[1 2 3 4 5]
(5,)


In [14]:
# Creating 2-D Array using list with array() function
import numpy as np
myarray2=np.array([[1,2,3],[4,5,6]])
print("Shape:",myarray2.shape)
print("Size:",myarray2.size)
print("Dimension:",myarray2.ndim)
print("Elements type:",myarray2.dtype)

Shape: (2, 3)
Size: 6
Dimension: 2
Elements type: int32


In [15]:
# Creating 3-D Array using list with array() function
import numpy as np
myarray2=np.array([[[1,2,3],[4,5,6]],[[1,1,1],[2,2,2]]])
print("Shape:",myarray2.shape)
print("Size:",myarray2.size)
print("Dimension:",myarray2.ndim)
print("Elements type:",myarray2.dtype)

Shape: (2, 2, 3)
Size: 12
Dimension: 3
Elements type: int32


In [18]:
#define the number of dimensions by using the ndmin argument.
myarray3=np.array([1,2,3,4],ndmin=5)
print(myarray3)
print("Shape:",myarray3.shape)
print("Size:",myarray3.size)
print("Dimension:",myarray3.ndim)
print("Elements type:",myarray3.dtype)

[[[[[1 2 3 4]]]]]
Shape: (1, 1, 1, 1, 4)
Size: 4
Dimension: 5
Elements type: int32


In [2]:
# Using arange() function to create a Numpy array
import numpy as np
myarray4=np.arange(1,11,2)
print(myarray4)
print("Shape:",myarray4.shape)
print("Size:",myarray4.size)
print("Dimension:",myarray4.ndim)
print("Elements type:",myarray4.dtype)

[1 3 5 7 9]
Shape: (5,)
Size: 5
Dimension: 1
Elements type: int32


In [2]:
import numpy as np
arr1=np.array([[1,2],[1,3],[1,4]])
arr2=np.array([[2,2],[2,2],[2,2]])
arr3=np.add(arr1,arr2)
print(arr3)

[[3 4]
 [3 5]
 [3 6]]


In [39]:
import numpy as np
myarray6=np.zeros([3,2],dtype=int)
print(myarray6)
print("Shape:",myarray6.shape)
print("Size:",myarray6.size)
print("Dimension:",myarray6.ndim)
print("Elements type:",myarray6.dtype)

[[0 0]
 [0 0]
 [0 0]]
Shape: (3, 2)
Size: 6
Dimension: 2
Elements type: int32


In [42]:
import numpy as np
myarray7=np.ones([3,2],dtype=int)
print(myarray7)
print("Shape:",myarray7.shape)
print("Size:",myarray7.size)
print("Dimension:",myarray7.ndim)
print("Elements type:",myarray7.dtype)

[[1 1]
 [1 1]
 [1 1]]
Shape: (3, 2)
Size: 6
Dimension: 2
Elements type: int32


In [46]:
import numpy as np
myarray8=np.asarray([1,2,3,4,5])
myarray8[2]=10
print(type(myarray8))
print("Shape:",myarray8.shape)
print("Size:",myarray8.size)
print("Dimension:",myarray8.ndim)
print("Elements type:",myarray8.dtype)

<class 'numpy.ndarray'>
Shape: (5,)
Size: 5
Dimension: 1
Elements type: int32


In [49]:
import numpy as np
arr = np.array([5,6,7])
x = np.array(arr)
y = np.asarray(arr)
arr[1] = 10
print("Array : ",x)
print("Asarray : ",y)

Array :  [5 6 7]
Asarray :  [ 5 10  7]


In [12]:
import numpy as np
myar=np.array([1,2,3,4,30])
class myArrayEx:
    arryop(self,ar[]):
        print(max(self.ar))
obj=myArrayEx()
obj.arrayop(myar)
        

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3385127409.py, line 4)